name: Sync Google Sheet to Repo

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Google Sheet CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRB-G_0OHce1UPa5HJjbMe5jT4qUQC26XZGQKOcXdf_uaHJgM-jZu3h4SvCBHGMW_ITwSOd3WrUFwMx/pub?gid=0&single=true&output=csv" -o data.csv

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.csv
          git commit -m "Update data.csv from Google Sheet" || echo "No changes"
          git push
